import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import { CAUSTIC_GLSL } from '../src/components/3d/caustics.ts';
import { FBM_GLSL } from '../src/components/3d/noiseColor.ts';

interface Reference {
  points: [number, number, number][];
  strength: number[];
  'tex_voronoi_5.2': number[];
  'tex_noise_1.7': number[];
  'tex_noise_3.6': number[];
}
// Generated by scripts/blender_caustic_reference.py from the source materials' own nodes.
const reference: Reference = JSON.parse(
  readFileSync(new URL('./fixtures/blender-caustic.json', import.meta.url), 'utf8'),
);

test('GLSL caustic port matches the submerged light emission in Chrome WebGL2', async ({ page }, info) => {
  await page.setContent('<canvas></canvas>');
  const results = await page.evaluate(
    ({ glsl, points }) => {
      const gl = document.querySelector('canvas')!.getContext('webgl2');
      if (!gl || !gl.getExtension('EXT_color_buffer_float')) throw Error('WebGL2 float render targets unavailable');
      const compile = (type: number, source: string) => {
        const shader = gl.createShader(type)!;
        gl.shaderSource(shader, source);
        gl.compileShader(shader);
        if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw Error(gl.getShaderInfoLog(shader) ?? 'compile');
        return shader;
      };
      const program = gl.createProgram()!;
      gl.attachShader(
        program,
        compile(
          gl.VERTEX_SHADER,
          `#version 300 es
in vec3 point;
uniform float count;
flat out vec3 vPoint;
void main() { vPoint = point; gl_PointSize = 1.0; gl_Position = vec4( ( float( gl_VertexID ) + 0.5 ) / count * 2.0 - 1.0, 0.0, 0.0, 1.0 ); }`,
        ),
      );
      gl.attachShader(
        program,
        compile(
          gl.FRAGMENT_SHADER,
          `#version 300 es
precision highp float;
precision highp int;
${glsl}
flat in vec3 vPoint;
out vec4 color;
void main() {
	vec3 warp = vPoint + 0.2 * sui_noise_color( vPoint * 3.6, 2.0, 0.0 );
	color = vec4( sui_caustic_strength( vPoint, 0.0 ), sui_voronoi_edge( warp * 5.2 ), sui_fbm( vPoint * 1.7, 3.0, 0.5, 2.0, 0.0 ), sui_fbm( vPoint * 3.6, 2.0, 0.5, 2.0, 0.0 ) );
}`,
        ),
      );
      gl.linkProgram(program);
      if (!gl.getProgramParameter(program, gl.LINK_STATUS)) throw Error(gl.getProgramInfoLog(program) ?? 'link');
      gl.useProgram(program);
      const count = points.length;
      const texture = gl.createTexture();
      gl.bindTexture(gl.TEXTURE_2D, texture);
      gl.texStorage2D(gl.TEXTURE_2D, 1, gl.RGBA32F, count, 1);
      gl.bindFramebuffer(gl.FRAMEBUFFER, gl.createFramebuffer());
      gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0);
      gl.viewport(0, 0, count, 1);
      gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer());
      gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(points.flat()), gl.STATIC_DRAW);
      const location = gl.getAttribLocation(program, 'point');
      gl.enableVertexAttribArray(location);
      gl.vertexAttribPointer(location, 3, gl.FLOAT, false, 0, 0);
      gl.uniform1f(gl.getUniformLocation(program, 'count'), count);
      gl.drawArrays(gl.POINTS, 0, count);
      const pixels = new Float32Array(count * 4);
      gl.readPixels(0, 0, count, 1, gl.RGBA, gl.FLOAT, pixels);
      return Array.from(pixels);
    },
    { glsl: FBM_GLSL + CAUSTIC_GLSL, points: reference.points },
  );
  const channels = ['strength', 'tex_voronoi_5.2', 'tex_noise_1.7', 'tex_noise_3.6'] as const;
  channels.forEach((name, c) => {
    const worst = Math.max(...reference[name].map((value, i) => Math.abs(value - results[i * 4 + c])));
    info.annotations.push({ type: 'max-abs-diff', description: `${name}: ${worst.toExponential(2)}` });
    expect(worst, name).toBeLessThan(1e-4);
  });
  // The fixture covers both lit points and the dark box outside the waterline.
  expect(reference.strength.filter((v) => v > 0.01).length).toBeGreaterThan(20);
  expect(reference.strength.filter((v) => v === 0).length).toBeGreaterThan(20);
});
