import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import { NOISE_COLOR_GLSL } from '../src/components/3d/noiseColor.ts';

interface Reference {
  lacunarity: number;
  points: [number, number, number][];
  configs: { scale: number; detail: number; roughness: number; values: number[] }[];
}
// Generated by scripts/blender_noise_reference.py with Blender's own Noise Texture node.
const reference: Reference = JSON.parse(readFileSync(new URL('./fixtures/blender-noise.json', import.meta.url), 'utf8'));

test('GLSL noise color port matches Blender noise in Chrome WebGL2', async ({ page }, info) => {
  await page.setContent('<canvas></canvas>');
  const results = await page.evaluate(({ glsl, reference }) => {
    const gl = document.querySelector('canvas')!.getContext('webgl2');
    if (!gl || !gl.getExtension('EXT_color_buffer_float')) throw Error('WebGL2 float render targets unavailable');
    const compile = (type: number, source: string) => {
      const shader = gl.createShader(type)!;
      gl.shaderSource(shader, source);
      gl.compileShader(shader);
      if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw Error(gl.getShaderInfoLog(shader) ?? 'compile');
      return shader;
    };
    const program = gl.createProgram()!;
    gl.attachShader(program, compile(gl.VERTEX_SHADER, `#version 300 es
in vec3 point;
uniform float count;
flat out vec3 vPoint;
void main() { vPoint = point; gl_PointSize = 1.0; gl_Position = vec4( ( float( gl_VertexID ) + 0.5 ) / count * 2.0 - 1.0, 0.0, 0.0, 1.0 ); }`));
    gl.attachShader(program, compile(gl.FRAGMENT_SHADER, `#version 300 es
precision highp float;
precision highp int;
${glsl}
flat in vec3 vPoint;
uniform float scale, detail, roughness, lacunarity, footprint;
out vec4 color;
void main() { color = vec4( sui_fbm( vPoint * scale, detail, roughness, lacunarity, footprint ), 0.0, 0.0, 1.0 ); }`));
    gl.linkProgram(program);
    if (!gl.getProgramParameter(program, gl.LINK_STATUS)) throw Error(gl.getProgramInfoLog(program) ?? 'link');
    gl.useProgram(program);
    const count = reference.points.length;
    const texture = gl.createTexture();
    gl.bindTexture(gl.TEXTURE_2D, texture);
    gl.texStorage2D(gl.TEXTURE_2D, 1, gl.RGBA32F, count, 1);
    gl.bindFramebuffer(gl.FRAMEBUFFER, gl.createFramebuffer());
    gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0);
    gl.viewport(0, 0, count, 1);
    gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer());
    gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(reference.points.flat()), gl.STATIC_DRAW);
    const location = gl.getAttribLocation(program, 'point');
    gl.enableVertexAttribArray(location);
    gl.vertexAttribPointer(location, 3, gl.FLOAT, false, 0, 0);
    const uniform = (name: string, value: number) => gl.uniform1f(gl.getUniformLocation(program, name), value);
    uniform('count', count);
    uniform('lacunarity', reference.lacunarity);
    const render = (config: Reference['configs'][number], footprint: number) => {
      uniform('scale', config.scale); uniform('detail', config.detail); uniform('roughness', config.roughness);
      uniform('footprint', footprint);
      gl.clear(gl.COLOR_BUFFER_BIT);
      gl.drawArrays(gl.POINTS, 0, count);
      const pixels = new Float32Array(count * 4);
      gl.readPixels(0, 0, count, 1, gl.RGBA, gl.FLOAT, pixels);
      return Array.from({ length: count }, (_, i) => pixels[i * 4]);
    };
    return reference.configs.map(config => ({ exact: render(config, 0), filtered: render(config, 1e3) }));
  }, { glsl: NOISE_COLOR_GLSL, reference });
  reference.configs.forEach((config, k) => {
    const worst = Math.max(...config.values.map((value, i) => Math.abs(value - results[k].exact[i])));
    info.annotations.push({ type: 'max-abs-diff', description: `scale ${config.scale} detail ${config.detail}: ${worst.toExponential(2)}` });
    expect(worst, `scale ${config.scale} detail ${config.detail}`).toBeLessThan(1e-4);
    // Octaves far below a pixel collapse to the noise mean instead of aliasing.
    for (const value of results[k].filtered) expect(value).toBeCloseTo(.5, 6);
  });
});
