import { readFileSync } from 'node:fs';
import { expect, test } from '@playwright/test';
import { SKY, SKY_BLEND_SHA256, SKY_GLSL } from '../src/components/3d/sky.ts';

type Vec3 = [number, number, number];
interface Reference {
  input_sha256: string;
  scenes: Record<
    'day' | 'evening' | 'night',
    { directions: Vec3[]; radiance: Vec3[]; voronoi: Vec3[]; noise: number[] }
  >;
}
// Generated by scripts/blender_sky_reference.py: Cycles panoramas of the source worlds.
const reference: Reference = JSON.parse(readFileSync(new URL('./fixtures/blender-sky.json', import.meta.url), 'utf8'));
const KEYS = ['day', 'evening', 'night'] as const;

test('GLSL sky port matches the Cycles worlds in Chrome WebGL2', async ({ page }, info) => {
  expect(reference.input_sha256, 'fixture and sky.json come from the same blend').toBe(SKY_BLEND_SHA256);
  await page.setContent('<canvas></canvas>');
  const results = await page.evaluate(
    ({ glsl, reference, keys, clouds }) => {
      const gl = document.querySelector('canvas')!.getContext('webgl2');
      if (!gl || !gl.getExtension('EXT_color_buffer_float')) throw Error('WebGL2 float render targets unavailable');
      const compile = (type: number, source: string) => {
        const shader = gl.createShader(type)!;
        gl.shaderSource(shader, source);
        gl.compileShader(shader);
        if (!gl.getShaderParameter(shader, gl.COMPILE_STATUS)) throw Error(gl.getShaderInfoLog(shader) ?? 'compile');
        return shader;
      };
      const program = gl.createProgram()!;
      gl.attachShader(
        program,
        compile(
          gl.VERTEX_SHADER,
          `#version 300 es
in vec3 point;
uniform float count;
flat out vec3 vPoint;
void main() { vPoint = point; gl_PointSize = 1.0; gl_Position = vec4( ( float( gl_VertexID ) + 0.5 ) / count * 2.0 - 1.0, 0.0, 0.0, 1.0 ); }`,
        ),
      );
      // A flat varying has zero derivatives: the sky is evaluated without its pixel filters.
      gl.attachShader(
        program,
        compile(
          gl.FRAGMENT_SHADER,
          `#version 300 es
precision highp float;
precision highp int;
${glsl}
flat in vec3 vPoint;
uniform int mode;
uniform float dusk, night;
uniform float starScale, bend, cloudScale;
uniform vec3 cloudOffset;
out vec4 color;
void main() {
	vec3 d = vPoint;
	if ( mode == 0 ) {
		// glTF axes of the Blender direction, through the same entry point as the scene.
		color = vec4( sui_sky( vec3( d.x, d.z, - d.y ), dusk, night ), 1.0 );
	} else if ( mode == 1 ) {
		vec3 cell;
		float dist = sui_voronoi_f1( d * starScale, cell );
		color = vec4( dist, cell.x, cell.y, 1.0 );
	} else {
		float denominator = max( d.z, 0.0 ) + bend;
		vec3 p = ( vec3( d.x / denominator, d.y / denominator, 0.0 ) + cloudOffset ) * cloudScale;
		color = vec4( sui_fbm( p, ${clouds.detail.toFixed(6)}, ${clouds.roughness.toFixed(6)}, ${clouds.lacunarity.toFixed(6)}, 0.0 ), 0.0, 0.0, 1.0 );
	}
}`,
        ),
      );
      gl.linkProgram(program);
      if (!gl.getProgramParameter(program, gl.LINK_STATUS)) throw Error(gl.getProgramInfoLog(program) ?? 'link');
      gl.useProgram(program);
      gl.uniform1f(gl.getUniformLocation(program, 'suiSkyDisk'), 1);
      gl.uniform1f(gl.getUniformLocation(program, 'starScale'), clouds.starScale);
      gl.uniform1f(gl.getUniformLocation(program, 'bend'), clouds.bend);
      gl.uniform1f(gl.getUniformLocation(program, 'cloudScale'), clouds.scale);
      gl.uniform3fv(gl.getUniformLocation(program, 'cloudOffset'), clouds.offset);
      const run = (points: number[][], mode: number, scene = 0) => {
        const count = points.length;
        const texture = gl.createTexture();
        gl.bindTexture(gl.TEXTURE_2D, texture);
        gl.texStorage2D(gl.TEXTURE_2D, 1, gl.RGBA32F, count, 1);
        gl.bindFramebuffer(gl.FRAMEBUFFER, gl.createFramebuffer());
        gl.framebufferTexture2D(gl.FRAMEBUFFER, gl.COLOR_ATTACHMENT0, gl.TEXTURE_2D, texture, 0);
        gl.viewport(0, 0, count, 1);
        gl.bindBuffer(gl.ARRAY_BUFFER, gl.createBuffer());
        gl.bufferData(gl.ARRAY_BUFFER, new Float32Array(points.flat()), gl.STATIC_DRAW);
        const location = gl.getAttribLocation(program, 'point');
        gl.enableVertexAttribArray(location);
        gl.vertexAttribPointer(location, 3, gl.FLOAT, false, 0, 0);
        gl.uniform1f(gl.getUniformLocation(program, 'count'), count);
        gl.uniform1i(gl.getUniformLocation(program, 'mode'), mode);
        // The weights of Blue hour and Night together and of Night (lighting.ts).
        gl.uniform1f(gl.getUniformLocation(program, 'dusk'), scene > 0 ? 1 : 0);
        gl.uniform1f(gl.getUniformLocation(program, 'night'), scene > 1 ? 1 : 0);
        gl.clear(gl.COLOR_BUFFER_BIT);
        gl.drawArrays(gl.POINTS, 0, count);
        const pixels = new Float32Array(count * 4);
        gl.readPixels(0, 0, count, 1, gl.RGBA, gl.FLOAT, pixels);
        return Array.from({ length: count }, (_, i) => [pixels[i * 4], pixels[i * 4 + 1], pixels[i * 4 + 2]]);
      };
      return keys.map((key, scene) => ({
        radiance: run(reference.scenes[key].directions, 0, scene),
        voronoi: run(reference.scenes[key].directions, 1),
        noise: run(reference.scenes[key].directions, 2).map((value) => value[0]),
      }));
    },
    {
      glsl: SKY_GLSL,
      reference,
      keys: KEYS,
      clouds: { ...SKY.day.clouds, starScale: SKY.day.stars.scale },
    },
  );
  KEYS.forEach((key, k) => {
    const scene = reference.scenes[key];
    const sky = SKY[key];
    expect(sky.clouds).toMatchObject({
      scale: SKY.day.clouds.scale,
      bend: SKY.day.clouds.bend,
      detail: SKY.day.clouds.detail,
    });
    expect(sky.stars.scale).toBe(SKY.day.stars.scale);
    // Points on a threshold of the graph (disk edge, star edge, star density) can fall either way.
    const onEdge = scene.directions.map((d, i) => {
      const cosSun = d[0] * sky.sun_direction[0] + d[1] * sky.sun_direction[1] + d[2] * sky.sun_direction[2];
      return (
        (sky.disk && Math.abs(cosSun - sky.disk_cos!) < 1e-5) ||
        Math.abs(scene.voronoi[i][0] - sky.stars.radius) < 1e-4 ||
        Math.abs(scene.voronoi[i][2] - sky.stars.density) < 1e-6
      );
    });
    const worst = (values: number[][], expected: number[][], relative: number) =>
      Math.max(
        ...values.flatMap((value, i) =>
          onEdge[i]
            ? []
            : value.map((v, c) => Math.abs(v - expected[i][c]) / (1e-4 + relative * Math.abs(expected[i][c]))),
        ),
      );
    const radiance = worst(results[k].radiance, scene.radiance, 1e-3);
    const voronoi = worst(results[k].voronoi, scene.voronoi, 0);
    const noise = worst(
      results[k].noise.map((v) => [v]),
      scene.noise.map((v) => [v]),
      0,
    );
    info.annotations.push({
      type: 'max-scaled-error',
      description: `${key}: radiance ${radiance.toFixed(3)}, voronoi ${voronoi.toFixed(3)}, noise ${noise.toFixed(3)}, skipped ${onEdge.filter(Boolean).length}`,
    });
    // Errors in units of the tolerance: 1e-4 absolute plus 0.1% of the radiance.
    expect(noise, `${key} noise`).toBeLessThan(1);
    expect(voronoi, `${key} voronoi`).toBeLessThan(1);
    expect(radiance, `${key} radiance`).toBeLessThan(1);
    // The sample hits the sun's disk and the clouds, not only the clear sky. The moon's 0.0093 rad
    // disk is smaller than a reference pixel, which then sees it only when its center falls inside.
    const inDisk = scene.directions.filter(
      (d) => d[0] * sky.sun_direction[0] + d[1] * sky.sun_direction[1] + d[2] * sky.sun_direction[2] > sky.disk_cos!,
    );
    if (key === 'day') expect(inDisk.length).toBeGreaterThan(0);
    if (sky.disk && inDisk.length) expect(scene.radiance.some((c) => c[0] > 100)).toBe(true);
    expect(scene.noise.filter((v) => v > (sky.clouds.low + sky.clouds.high) / 2).length).toBeGreaterThan(10);
  });
});
